server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**
        - id: HrSystem
          uri: http://localhost:8082
          predicates:
            - Path=/hrSyetems/**
        - id: Reservation
          uri: http://localhost:8083
          predicates:
            - Path=/reservations/**
        - id: orderstatus
          uri: http://localhost:8084
          predicates:
            - Path=/orderStatuses/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://jhoneyorder:8080
          predicates:
            - Path=/orders/**
        - id: HrSystem
          uri: http://jhoneyhrsystem:8080
          predicates:
            - Path=/hrSystems/**
        - id: Reservation
          uri: http://jhoneyreservation:8080
          predicates:
            - Path=/reservations/**
        - id: orderstatus
          uri: http://jhoneyorderstatus:8080
          predicates:
            - Path=/orderStatuses/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
